# Generated by Django 4.2.11 on 2024-03-15 16:59

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('round', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=512, null=True, verbose_name='عنوان کد')),
                ('code', models.CharField(blank=True, max_length=512, null=True, verbose_name='کد تخفیف')),
                ('percent', models.IntegerField(blank=True, null=True, verbose_name='درصد تخفیف')),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='میزان تخفیف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('created_ja_at', models.CharField(default='1402/12/25', max_length=10, verbose_name='تاریخ شمسی')),
                ('round', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='round_discount_code', to='round.round', verbose_name='دوره')),
            ],
            options={
                'verbose_name': 'کد تخفیف',
                'verbose_name_plural': 'کد تخفیف ها',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=512, null=True, verbose_name='نام تیم')),
                ('school', models.CharField(blank=True, max_length=512, null=True, verbose_name='نام مدرسه')),
                ('city', models.CharField(blank=True, max_length=512, null=True, verbose_name='نام شهر')),
                ('grade', models.CharField(blank=True, choices=[('7', 'هفتم'), ('8', 'هشتم'), ('9', 'نهم')], max_length=128, null=True, verbose_name='مقطع تحصیلی')),
                ('username', models.CharField(blank=True, max_length=512, null=True, verbose_name='نام کاربری')),
                ('password', models.CharField(blank=True, max_length=512, null=True, verbose_name='رمز عبور')),
                ('first_name_1', models.CharField(blank=True, max_length=512, null=True, verbose_name='نام شرکت کننده اول')),
                ('last_name_1', models.CharField(blank=True, max_length=512, null=True, verbose_name='نام خانوادگی شرکت کننده اول')),
                ('national_code_1', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='کد ملی شرکت کننده اول')),
                ('phone_1', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='شماره موبایل شرکت کننده اول')),
                ('parent_phone_1', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='شماره موبایل والدین شرکت کننده اول')),
                ('email_1', models.EmailField(blank=True, max_length=255, null=True, verbose_name='آدرس ایمیل شرکت کننده اول')),
                ('first_name_2', models.CharField(blank=True, max_length=512, null=True, verbose_name='نام شرکت کننده دوم')),
                ('last_name_2', models.CharField(blank=True, max_length=512, null=True, verbose_name='نام خانوادگی شرکت کننده دوم')),
                ('national_code_2', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='کد ملی شرکت کننده دوم')),
                ('phone_2', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='شماره موبایل شرکت کننده دوم')),
                ('parent_phone_2', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='شماره موبایل والدین شرکت کننده دوم')),
                ('email_2', models.EmailField(blank=True, max_length=255, null=True, verbose_name='آدرس ایمیل شرکت کننده دوم')),
                ('pyment_status', models.CharField(choices=[('waiting', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('unpaid', 'پرداخت نشده')], default='waiting', max_length=128, verbose_name='وضعیت پرداخت')),
                ('pyment_serial', models.CharField(blank=True, max_length=512, null=True, verbose_name='شماره پیگیری')),
                ('active', models.BooleanField(default=False, verbose_name='فعال بودن')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('created_ja_at', models.CharField(default='1402/12/25', max_length=10, verbose_name='تاریخ شمسی')),
                ('discount_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_code_team', to='team.discountcode', verbose_name='تخفیف')),
                ('round', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='round_team', to='round.round', verbose_name='دوره')),
            ],
            options={
                'verbose_name': 'تیم',
                'verbose_name_plural': 'تیم ها',
                'ordering': ('-created_at',),
            },
        ),
    ]
